### ISSUE TITLE
Generating video data

### ISSUE THREAD

**Issue by wilson1yan** [mugen-org/MUGEN_coinrun#1]
Hi,

I'm having trouble getting the dataset. I have the data downloaded from the website, but it doesn't seem like it has the video data. I assume I need to generate it, but I'm not too sure how to since neither `gen_videos.sh` nor `gen_videos.py` work for me.

`gen_videos.sh` seems to expect some `monitor.csv` file that doesn't exist in the download files, and `gen_videos.py` expects some audio semantic map folder that doesn't exist.

How can I get the video data?

**Comment by Sy-Zhang** [comment]
> Hi,
> 
> I'm having trouble getting the dataset. I have the data downloaded from the website, but it doesn't seem like it has the video data. I assume I need to generate it, but I'm not too sure how to since neither `gen_videos.sh` nor `gen_videos.py` work for me.
> 
> `gen_videos.sh` seems to expect some `monitor.csv` file that doesn't exist in the download files, and `gen_videos.py` expects some audio semantic map folder that doesn't exist.
> 
> How can I get the video data?


We have not uploaded the mp4 videos themselves, but videos can be generated by loading the game metadata json and rendering them with the data loader provided in the released code: https://github.com/mugen-org/MUGEN_baseline/blob/main/lib/data/mugen_data.py#L148. This allows you to render the video frames at any resolution on the fly. As for audio, there should be already rendered audio in the [coinrun.zip](http://coinrun.zip/) under mix_audio.

**Comment by wilson1yan** [comment]
Thanks!
